version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: docker-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - app-network

  nginx:
    image: nginx:1.19-alpine
    container_name: docker-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - app-network

  db:
    image: postgres:9.6
    container_name: docker-db
    restart: always
    ports: 
      - 5432:5432
    volumes:
      - ./docker/pgsql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
